apiVersion: apps/v1
kind: Deployment
metadata:
  name: callcenter-test
  namespace: kenny
  labels:
    app: callcenter-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callcenter-test
  template:
    metadata:
      labels:
        app: callcenter-test
    spec:
      containers:
        - name: callcenter-test
          image: mtl-docker-test.aimfire.net:5000/kenny-callcenter:test-0.8.0
          ports:
            - name: app-port
              containerPort: 80
          resources:
            limits:
              memory: "32Mi"
              cpu: "100m"
              
---
apiVersion: v1
kind: Service
metadata:
  name: callcenter-test
  namespace: kenny
spec:
  type: NodePort
  selector:
    app: callcenter-test
  ports:
    - protocol: TCP
      nodePort: 30240
      port: 80
      targetPort: app-port
