version: "3"
services:
 
  app:
    build:
      context: .
      args:
        ENV: ${ENV}
    image: mtl-docker-test.aimfire.net:5000/kenny-callcenter:${ENV}-${VERSION}
    ports:
      - "${APP_PORT}:80"
    restart: unless-stopped
