import { FormGroup, FormControl } from '@angular/forms';
import { Injectable } from '@angular/core';
import { cloneDeep } from 'lodash';

@Injectable({
  providedIn: 'root'
})
export class FormGroupService {

  fg: FormGroup = new FormGroup({
    callNote: new FormControl(''),
    // header form
    date: new FormControl(new Date()),
    contactName: new FormControl(''),
    draftAgent: new FormControl(''),
    email: new FormControl(''),
    phone: new FormControl(''),
    wonAgent: new FormControl(''),
    mobile: new FormControl(''),
    action: new FormControl(''),
    vehiclePostalCode: new FormControl(''),
    vin: new FormControl(''),
    checksum: new FormControl(''),
    company: new FormControl(''),
    make: new FormControl(''),
    model: new FormControl(''),
    year: new FormControl(''),
    mileage: new FormControl(''),
    unit: new FormControl(''),
    carBody: new FormControl(false),
    vehicleAccidented: new FormControl(false),
    front: new FormControl(false),
    left: new FormControl(false),
    right: new FormControl(false),
    back: new FormControl(false),
    haveKeys: new FormControl(false),
    haveOwnershipPaper: new FormControl(false),
    powerAttorney: new FormControl(false),
    picture1: new FormControl(''),
    picture2: new FormControl(''),
    picture3: new FormControl(''),
    picture4: new FormControl(''),
    picture5: new FormControl(''),
    freeDebt: new FormControl(''),
    // missing parts tab
    haveEngine: new FormControl(''),
    engineDeduction: new FormControl(0),
    engineRun: new FormControl(''),
    engineLight: new FormControl(''),
    haveTransmission: new FormControl(''),
    transmissionDeduction: new FormControl(0),
    transmissionRunning: new FormControl(''),
    haveBattery: new FormControl(''),
    batteryDeduction: new FormControl(0),
    haveCatalyticConvertor: new FormControl(''),
    catalyticConvertorDeduction: new FormControl(0),
    haveTires: new FormControl(''),
    missingQuantityTires: new FormControl(0),
    tiresDeduction: new FormControl(0),
    haveRims: new FormControl(''),
    missingQuantityRims: new FormControl(0),
    rimsDeduction: new FormControl(0),
    haveAC: new FormControl(''),
    rust: new FormControl(''),
    mechanicalNote: new FormControl(''),
    // offer tab
    dropOff: new FormControl(false),
    missingPartsDeduction: new FormControl(0),
    distanceFreeDeduction: new FormControl(0),
    costumerExpectation: new FormControl(''),
    agentOffer: new FormControl(''),
    offerAccepted: new FormControl(true),
    secondOffer: new FormControl(''),
    secondAgent: new FormControl(''),
    refusalReason: new FormControl(''),
    offerDifference: new FormControl(''),
    // secondary info
    color: new FormControl(''),
    engineSize: new FormControl(''),
    transmission: new FormControl(''),
    bodyType: new FormControl(''),
    style: new FormControl(''),
    license: new FormControl(''),
    driveline: new FormControl(''),
    certificate: new FormControl(''),
    engineType: new FormControl(''),
    grossWeight: new FormControl(''),
    uom: new FormControl(''),
    // supplier and owner info
    supplier: new FormControl(''),
    preferredLanguage: new FormControl(''),
    fiscalPosition: new FormControl(''),
    contactSource: new FormControl(''),
    supplierAddress: new FormControl(''),
    supplierCity: new FormControl(''),
    supplierProvince: new FormControl(''),
    supplierPostalCode: new FormControl(''),
    supplierCountry: new FormControl(''),
    supplierPhone: new FormControl(''),
    supplierCellulaire: new FormControl(''),
    isSupplierOwner: new FormControl(false),
    owner: new FormControl(''),
    ownerAddress: new FormControl(''),
    ownerCity: new FormControl(''),
    ownerProvince: new FormControl(''),
    ownerPostalCode: new FormControl(''),
    ownerCountry: new FormControl(''),
    ownerEmail: new FormControl(''),
    ownerPhone: new FormControl(''),
    ownerCellulaire: new FormControl(''),
    isOwnerDonor: new FormControl(''),
    donor: new FormControl(''),
    donorAddress: new FormControl(''),
    donorCity: new FormControl(''),
    donorProvince: new FormControl(''),
    donorPostalCode: new FormControl(''),
    donorCountry: new FormControl(''),
    donorEmail: new FormControl(''),
    donorPhone: new FormControl(''),
    donorCellulaire: new FormControl(''),
    donorDriverLicense: new FormControl(''),
    donorReference: new FormControl(''),
    donorLanguage: new FormControl(''),
    donorTaxCreditByEmail: new FormControl(''),
    donorCommemorativeCard: new FormControl(''),
    donorCardInMemoryOf: new FormControl(''),
    donorInfo: new FormControl(''),
    // towing and recap
    pickupDate: new FormControl(''),
    pickupType: new FormControl(''),
    paymentMethod: new FormControl(''),
    delayReason: new FormControl(''),
    towingAddressOption: new FormControl(''),
    towingAddress: new FormControl(''),
    towingCity: new FormControl(''),
    towingProvince: new FormControl(''),
    towingPostalCode: new FormControl(''),
    towingCountry: new FormControl(''),
    towingPhone: new FormControl(''),
    towingCellulaire: new FormControl(''),
    wheels: new FormControl(''),
    tires: new FormControl(''),
    brakes: new FormControl(''),
    differentCarLocation: new FormControl(false),
    carLocation: new FormControl(''),
    burntCar: new FormControl(false),
    ownershipTransferDisclaimer: new FormControl(false),
    vehicleHybrid: new FormControl(false),
    hybridNote: new FormControl(''),
    charityNote: new FormControl(''),
    towingNote: new FormControl(''),
    goodForSaleNote: new FormControl(''),
  });

  constructor() { }

  resetFormGroup() {
    sessionStorage.removeItem('formGroup');

    const inputValues = {
      callNote: '',
      // header form
      date: new Date(),
      contactName: '',
      draftAgent: '',
      email: '',
      phone: '',
      wonAgent: '',
      mobile: '',
      action: '',
      vehiclePostalCode: '',
      vin: '',
      checksum: '',
      company: '',
      make: '',
      model: '',
      year: '',
      mileage: '',
      carBody: false,
      vehicleAccidented: false,
      front: false,
      left: false,
      right: false,
      back: false,
      haveKeys: false,
      haveOwnershipPaper: false,
      powerAttorney: false,
      picture1: '',
      picture2: '',
      picture3: '',
      picture4: '',
      picture5: '',
      freeDebt: '',
      // missing parts tab
      haveEngine: '',
      engineDeduction: 0,
      engineRun: '',
      engineLight: '',
      haveTransmission: '',
      transmissionDeduction: 0,
      transmissionRunning: '',
      haveBattery: '',
      batteryDeduction: 0,
      haveCatalyticConvertor: '',
      catalyticConvertorDeduction: 0,
      haveTires: '',
      missingQuantityTires: 0,
      tiresDeduction: 0,
      haveRims: '',
      missingQuantityRims: 0,
      rimsDeduction: 0,
      haveAC: '',
      rust: '',
      mechanicalNote: '',
      // offer tab
      dropOff: false,
      missingPartsDeduction: 0,
      distanceFreeDeduction: 0,
      costumerExpectation: '',
      offerAccepted: true,
      agentOffer: '',
      secondOffer: '',
      secondAgent: '',
      refusalReason: '',
      offerDifference: '',
      // secondary info
      color: '',
      engineSize: '',
      transmission: '',
      bodyType: '',
      style: '',
      license: '',
      driveline: '',
      certificate: '',
      engineType: '',
      grossWeight: '',
      uom: '',
      // supplier and owner info
      supplier: '',
      preferredLanguage: '',
      fiscalPosition: '',
      contactSource: '',
      supplierAddress: '',
      supplierCity: '',
      supplierProvince: '',
      supplierPostalCode: '',
      supplierCountry: '',
      supplierPhone: '',
      supplierCellulaire: '',
      isSupplierOwner: false,
      owner: '',
      ownerAddress: '',
      ownerCity: '',
      ownerProvince: '',
      ownerPostalCode: '',
      ownerCountry: '',
      ownerEmail: '',
      ownerPhone: '',
      ownerCellulaire: '',
      donor: '',
      donorAddress: '',
      donorCity: '',
      donorProvince: '',
      donorPostalCode: '',
      donorCountry: '',
      donorPhone: '',
      donorCellulaire: '',
      donorDriverLicense: '',
      donorReference: '',
      donorCorrespondece: '',
      donorTaxCreditByEmail: '',
      donorCommemorativeCard: '',
      donorCardInMemoryOf: '',
      donorInfo: '',
      // towing and recap
      pickupDate: '',
      pickupType: '',
      delayReason: '',
      towingAddressOption: '',
      towingAddress: '',
      towingCity: '',
      towingProvince: '',
      towingPostalCode: '',
      towingCountry: '',
      towingPhone: '',
      towingCellulaire: '',
      wheels: '',
      paymentMethod: '',
      tires: '',
      brakes: '',
      differentCarLocation: false,
      carLocation: '',
      burntCar: false,
      ownershipTransferDisclaimer: false,
      vehicleHybrid: false,
      hybridNote: '',
      charityNote: '',
      towingNote: '',
      goodForSaleNote: '',
    };
    this.fg.patchValue(inputValues);
  }

}
